name: Build-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\OriDETracker\OriDETracker.sln /p:Configuration=Release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: artifact
          path: ${{ github.workspace }}\OriDETracker\bin\Release\
